on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v40.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
